version: '2'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "127.0.0.1:33060:3306"
    volumes:
      - data-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: unless-stopped
  guacd:
    image: guacamole/guacd:1.5.3
    depends_on:
      - db
    restart: unless-stopped
  guacamole:
    image: guacamole/guacamole:1.5.3
    #image: a5fad0117bce
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    ports:
      - "127.0.0.1:8380:8080"
    depends_on:
      - guacd
      - db
    restart: unless-stopped
volumes:
  data-volume:
