version: '2'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "127.0.0.1::33060:3306"
    volumes:
      - data-volume:/var/lib/mysql
  guacd:
    image: guacamole/guacd:latest
  guacamole:
    image: guacamole/guacamole:latest
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "127.0.0.1:8080:8080"
volumes:
  data-volume:

